# Site settings
title: සිංහල අකුරු හා ටෙෙපොග්‍රැෆි නිර්මාණකරණ තරග අවකාශය
tag_text: සිංහල අකුරු හා ටෙෙපොග්‍රැෆි නිර්මාණකරණ තරග අවකාශය
description: සිංහල අකුරු හා ටෙෙපොග්‍රැෆි නිර්මාණකරණ තරග අවකාශය


# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
